### ISSUE TITLE
Console vs HTML Preview

### ISSUE THREAD

**Issue by voronianski** [voronianski/esnextbin#10]
I think that we need one more switch between HTML Preview and Console that will add more REPL like experience.

**Comment by gunar** [comment]
I was going to open this issue. This is surely the last feature I need for ESNextbin to be my de facto go to for rapid prototyping. 100% better than the others!

**Comment by voronianski** [comment]
@gunar thanks, will try to deliver it asap

**Comment by axefrog** [comment]
JSBin is a good example to follow. Just make it so you can hide and show different views as needed.

**Comment by voronianski** [comment]
@axefrog I'm thinking just to add switch between HTML and Console output. I don't want to introduce complexity with "JSBin-like" design.

**Comment by voronianski** [comment]
btw, guys, @gunar @axefrog, maybe you can advice good console/repl imitation lib?

**Comment by voronianski** [comment]
hmm, maybe this one https://github.com/chibicode/react-json-tree will be enough.

**Comment by gunar** [comment]
I don't, but this looks good ^

**Comment by nfcampos** [comment]
@voronianski this is better for actually imitating the console in the web inspector https://github.com/xyc/react-inspector not sure that's better for this though

**Comment by peduarte** [comment]
What I love the most ESNextbin is how simple it is! I think that adding an option to switch between HTML Preview and Console might take away a bit of this simplicity.

I see the benefit of being able to hide the HTML preview panel, however I think we can rely on the Console from Dev Tools rather than having one built in.

For example, here's a screen shot of how it'd look:

<img width="1280" alt="screenshot 2016-11-05 20 31 21" src="https://cloud.githubusercontent.com/assets/372831/20033369/d73df316-a396-11e6-914a-ceb2e3087d89.png">

It's just an idea, but it'd be nice to keep this as simple as it as and will keep it easier to maintain.

Thanks!
