### ISSUE TITLE
GitHub integration is broken

### ISSUE THREAD

**Issue by notpushkin** [voronianski/esnextbin#161]
When I click “save (secret) Gist”, it opens a ton of authorization popups and does nothing else.

Probably something broke because https://labs.voronianski.com/gatekeeper/token.php is down (says that the hosting plan is expired)?

**Comment by iamale** [comment]
Also, after pressing “Execute” for the second time, ESNextBin hangs loading while a request to token.php is being made (which in our case means indefinitely because your hosting provider sends a response without CORS and either the browser or the `request` library don't pass it to your code). First “execution” works OK though.

**Comment by odyright** [comment]
same issues ...

**Comment by voronianski** [comment]
@iamale @odyright sorry, guys.. I'm looking into the issue, hopefully it will get back very soon!

**Comment by voronianski** [comment]
fixed
